# Generated by Django 2.2 on 2019-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('img_file', models.CharField(blank=True, max_length=500)),
                ('img_caption', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=500)),
                ('formula', models.CharField(blank=True, max_length=500)),
                ('strunz', models.CharField(blank=True, max_length=500)),
                ('color', models.CharField(blank=True, max_length=500)),
                ('crystal_sys', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(blank=True, max_length=500)),
                ('crystal_sym', models.CharField(blank=True, max_length=500)),
                ('cleavage', models.CharField(blank=True, max_length=500)),
                ('mohs', models.CharField(blank=True, max_length=500)),
                ('luster', models.CharField(blank=True, max_length=500)),
                ('streak', models.CharField(blank=True, max_length=500)),
                ('diaphaneity', models.CharField(blank=True, max_length=500)),
                ('optical', models.CharField(blank=True, max_length=500)),
                ('refractive', models.CharField(blank=True, max_length=500)),
                ('crystal_habit', models.CharField(blank=True, max_length=500)),
                ('specific_gravity', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
